### ISSUE TITLE
0.000000000000000000000000000000000000000000000000000000000000000000000000000000034%

### ISSUE THREAD

**Issue by Luna5829** [xHERMIS/ID-to-TOKEN#9]
the chances of this script actually guessing the token correctly is 1 in 29600000000000000000000000000000000000000000000000000000000000000000000000000000
or
0.0000000000000000000000000000000000000000000000000000000000000000000000000000034%

**Comment by Luna5829** [comment]
generate_random_string has 64 possible characters, the total amount of random characters in the token is 44 (6+38)
64^44=the big number beginning with 296
1/big number*100 gets you the percentage

**Comment by xHERMIS** [comment]
https://github.com/xHERMIS/ID-to-TOKEN?tab=readme-ov-file#-important

**Comment by stefnotch** [comment]
The readme is still wrong, as it's missing a lot of zeroes. It's off by a few orders of magnitude.

By the way, part of the reason why you're getting "issue reports" isn't even because this statistically doesn't work.
Instead it's because the majority of "Discord XYZ" scripts on GitHub are scams. Which is by no means your fault, but I thought it'd be important to let you know.

**Comment by ingoau** [comment]
and i thought the discord nitro gift link generator and checker was stupid...

**Comment by ingoau** [comment]
> The readme is still wrong, as it's missing a lot of zeroes. It's off by a few orders of magnitude.

#18 someone had to do it
